#!/bin/sh

set -e

case "$1" in 
  remove|purge)
	if [ -L /etc/X11/app-defaults/XScreenSaver ]; then
	    if [ "$(readlink /etc/X11/app-defaults/XScreenSaver)" = "XScreenSaver-gl" ]; then
		if [ -e /etc/X11/app-defaults/XScreenSaver-nogl ]; then
		    ln -sf XScreenSaver-nogl /etc/X11/app-defaults/XScreenSaver.dpkg-new
		    mv -f /etc/X11/app-defaults/XScreenSaver.dpkg-new /etc/X11/app-defaults/XScreenSaver
		else
		    rm -f /etc/X11/app-defaults/XScreenSaver
		fi
	    fi
	fi
	;;
esac

#DEBHELPER#
